### ISSUE TITLE
0.1.6.8 has not been uploaded to Hackage

### ISSUE THREAD

**Issue by rhymoid** [UU-ComputerScience/uhc-util#12]
UHC depends on `uhc-util >=0.1.6.8 && <0.1.7`, but the most recent version on Hackage is 0.1.6.7.

**Comment by atzedijkstra** [comment]
Hi Stijn,

Uhc and uhc-util both taken from github or both from hackage are version consistent, and if uploaded/updated to hackage they are updated together. This is to prevent other version related problems.

Regards
Atze


--
Atze Dijkstra

**Comment by rhymoid** [comment]
Got it. I mixed GitHub (uhc) and Hackage (uhc-util).
