### ISSUE TITLE
Missing UHC/Util/Hashable.hs

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc-util#2]
I couldn't install the development version of the library:

    $ cabal install
    ...
    cabal: can't find source for UHC/Util/Hashable in src, dist/build/autogen
    Failed to install uhc-util-0.1.5.1

**Comment by uhc** [comment]
Has been added.

> On  26 Mar, 2015, at 14:38 , Andrés Sicard-Ramírez <notifications@github.com> wrote:
> 
> I couldn't install the development version library:
> 
> $ cabal install
> ...
> cabal: can't find source for UHC/Util/Hashable in src, dist/build/autogen
> Failed to install uhc-util-0.1.5.1
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by asr** [comment]
Thanks!
