### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by asr** [UU-ComputerScience/uhc-util#3]
If the library is called `uhc-util` why this repository hasn't the same name?

**Comment by uhc** [comment]
This was a typo error on my part at the time I created the repo. I have fixed this.

Atze

> On  26 Mar, 2015, at 14:46 , Andrés Sicard-Ramírez <notifications@github.com> wrote:
> 
> If the library is called uhc-util why this repository hasn't the same name?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


                - Atze -

Atze Dijkstra, Department of Information and Computing Sciences. /|\
Utrecht University, PO Box 80089, 3508 TB Utrecht, Netherlands. / | \
Tel.: +31-30-2534118/1454 | WWW  : http://www.cs.uu.nl/~atze . /--|  \
Fax : +31-30-2513971 .... | Email: atze@uu.nl ............... /   |___\

**Comment by asr** [comment]
Thanks!
