### ISSUE TITLE
Strictness of "sortOn" has changed with GHC 7.10

### ISSUE THREAD

**Issue by phile314** [UU-ComputerScience/uhc-util#5]
UHC.Util.Utils.sortOn uses the builtin Data.List.sortOn with GHC 7.10 or later. On earlier GHCs, an own custom implementation is used. See https://github.com/UU-ComputerScience/uhc-util/blob/master/src/UHC/Util/Utils.hs#L252-257 .

These two implementations have slightly different strictness, where the Data.List.sortOn version seems to be slightly more strict.

This causes a shuffle error when compiling UHC, see http://hydra.cryp.to/build/787325/nixlog/3/raw . The call to sortOn causing the
problem is at https://github.com/UU-ComputerScience/shuffle/blob/master/src/UHC/Shuffle/Common.hs#L373-382 .

I see two possible solutions:
1. Use the old custom sortOn implementation also for newer GHC versions
2. Fix call sites to not rely on the lazyness of sortOn.
   There are 19 calls to sortOn in UHC plus 2 more in shuffle, but I have no idea if
   any of them rely on the lazyness of sortOn.

@atzedijkstra I prefer the first solution, as hunting down problems with
lazyness/strictness isn't that much fun. Which option do you prefer?

( see also https://github.com/UU-ComputerScience/shuffle/pull/4 .)

**Comment by atzedijkstra** [comment]
Solution 1, using an older version of sortOn seems to me the best. In my opinion a stricter sortOn should have been given a different name...

A


--
Atze Dijkstra

**Comment by phile314** [comment]
The above commits make it possible to build UHC with GHC 7.10. Compiling & running a HelloWorld Haskell program works with UHC compiled by GHC 7.10.

I chose to rename sortOn to sortOnLazy, to make it more clear that it's semantics are slightly different. It also makes dealing with the import/export lists slightly easier, but changing it back to sortOn is also possible if you prefer that. uuagc doesn't use "sortOn", so it doesn't matter for that package.

I'm going to open pull requests now.
